#!/bin/bash
yum install 'tex(quotchap.sty)' 'tex(wrapfig.sty)' 'tex(nag.sty)' 'tex(siunitx.sty)' 'tex(xy.sty)' 'tex(xmpincl.sty)' 'tex(xmpincl.sty)' 'tex(mhchem.sty)' texlive-minitoc
yum install tetex-fonts
