name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Latex
      run: sudo apt install texlive-latex-extra texlive-fonts-extra fig2dev tetex-fonts texlive-minitoc.noarch transfig texlive-babel-latin 'tex(siunitx.sty)' texlive-gitinfo texlive-ccicons

    - name: Install dependencies
      run: make

