name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: test
      run: sudo apt install apt-file & sudo apt-file find "minitoc.sty"


    - name: Install Latex
      run: sudo apt install texlive-latex-extra texlive-fonts-extra fig2dev texlive-minitoc.noarch transfig

    - name: Install dependencies
      run: make

