name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: setup_images
#      run: sudo apt install fig2dev transfig inkscape
#    - name: images
#      run: make images
    - name: compile latex
      uses: xu-cheng/latex-action@v2
      with:
        root_file: fisica_linux.tex
        args: -pdf -file-line-error  -interaction=nonstopmode -shell-escape
        latexmk_shell_escape: true
        continue_on_error: true

#    - name: test1
#      run: sudo apt install apt-file

#    - name: test2
#      run: |
#        sudo apt-file update 
#        sudo apt-file find "minitoc.sty"

    #- name: Install Latex
    #  run: sudo apt install texlive-latex-extra texlive-fonts-extra texlive-lang-italian texlive-science fig2dev transfig inkscape

    #- name: Make
    #  run: make

